name: hcase
channels:
  - defaults
  - conda-forge
dependencies:
  - rdkit==2018.09.1.0
  - networkx==2.4
  - notebook==6.1.4
  - hilbertcurve=1.0.3
  - python=3.7
  - matplotlib=3.4
  - pip=22.3.1
  - scipy=1.7.3
  - seaborn=0.11.2
  - pip:
      - scikit-learn==1.0.2
